-- MySQL Script generated by MySQL Workbench
-- Wed Mar 25 19:26:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema d_PersonnelManagementSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema d_PersonnelManagementSystem
-- -----------------------------------------------------
drop database if exists `d_PersonnelManagementSystem`;
CREATE SCHEMA IF NOT EXISTS `d_PersonnelManagementSystem` DEFAULT CHARACTER SET utf8 ;
USE `d_PersonnelManagementSystem` ;

-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_archives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_archives` (
  `pk_aid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT(11) NOT NULL,
  `sex` CHAR(2) NOT NULL,
  `img` VARCHAR(100) NULL DEFAULT NULL,
  `idcard` VARCHAR(18) NOT NULL,
  `nativePlace` VARCHAR(45) NOT NULL COMMENT '籍贯',
  `politicsStatus` VARCHAR(10) NOT NULL COMMENT '政治面貌',
  `tel` INT(11) NOT NULL,
  `eMail` VARCHAR(45) NOT NULL,
  `education` VARCHAR(45) NOT NULL COMMENT '学历',
  `university` VARCHAR(45) NOT NULL COMMENT '大学',
  `major` VARCHAR(45) NOT NULL COMMENT '专业',
  PRIMARY KEY (`pk_aid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `idcard_UNIQUE` (`idcard` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '员工档案';


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_department` (
  `pk_did` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `manager` VARCHAR(45) NOT NULL,
  `tel` INT(11) NOT NULL,
  PRIMARY KEY (`pk_did`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_position` (
  `pk_pid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `salary` DOUBLE NOT NULL,
  `fk_did` INT(11) NOT NULL,
  PRIMARY KEY (`pk_pid`),
  INDEX `fk_t_employee_position_t_employee_department1_idx` (`fk_did` ASC),
  CONSTRAINT `fk_t_employee_position_t_employee_department1`
    FOREIGN KEY (`fk_did`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_department` (`pk_did`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_train` (
  `pk_etid` INT(11) NOT NULL AUTO_INCREMENT,
  `isTraining` INT(11) NOT NULL,
  `bak1` VARCHAR(500) NULL DEFAULT NULL,
  `bak2` VARCHAR(45) NULL DEFAULT NULL,
  `bak3` VARCHAR(45) NULL DEFAULT NULL,
  `bak4` VARCHAR(45) NULL DEFAULT NULL,
  `bak5` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_etid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_infomation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_infomation` (
  `pk_eid` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_pid` INT(11) NOT NULL,
  `fk_aid` INT(11) NOT NULL,
  `jointime` DATE NULL DEFAULT NULL,
  `boss` INT(11) NULL DEFAULT NULL,
  `fk_etid` INT(11) NOT NULL,
  `Positivedates` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`pk_eid`),
  INDEX `fk_t_employee_infomation_t_employee_position1_idx` (`fk_pid` ASC),
  INDEX `fk_t_employee_infomation_t_employee_archives1_idx` (`fk_aid` ASC),
  INDEX `fk_t_employee_infomation_t_employee_train1_idx` (`fk_etid` ASC),
  CONSTRAINT `fk_t_employee_infomation_t_employee_archives1`
    FOREIGN KEY (`fk_aid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_archives` (`pk_aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_employee_infomation_t_employee_position1`
    FOREIGN KEY (`fk_pid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_position` (`pk_pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_employee_infomation_t_employee_train1`
    FOREIGN KEY (`fk_etid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_train` (`pk_etid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_attendance_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_attendance_time` (
  `pk_attid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `start` TIME NOT NULL,
  `end` TIME NOT NULL,
  PRIMARY KEY (`pk_attid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_attendance` (
  `pk_atid` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_attid` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `fk_eid` INT(11) NOT NULL,
  PRIMARY KEY (`pk_atid`),
  INDEX `fk_t_user_attended_t_user_attended_time1_idx` (`fk_attid` ASC),
  INDEX `fk_t_employee_attendance_t_employee_infomation1_idx` (`fk_eid` ASC),
  CONSTRAINT `fk_t_employee_attendance_t_employee_infomation1`
    FOREIGN KEY (`fk_eid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_infomation` (`pk_eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_attended_t_user_attended_time1`
    FOREIGN KEY (`fk_attid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_attendance_time` (`pk_attid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_attendance_signin_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_attendance_signin_type` (
  `pk_sitid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_sitid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_attendance_signout_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_attendance_signout_type` (
  `pk_sotid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_sotid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_attendance_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_attendance_detail` (
  `pk_atdid` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_signoutid` INT(11) NOT NULL,
  `fk_signinid` INT(11) NOT NULL,
  `isleave` INT(11) NULL DEFAULT NULL,
  `fk_atid` INT(11) NOT NULL,
  PRIMARY KEY (`pk_atdid`),
  INDEX `fk_t_user_attendance_t_user_attendance_signout_type1_idx` (`fk_signoutid` ASC),
  INDEX `fk_t_user_attendance_t_user_attendance_signin_type1_idx` (`fk_signinid` ASC),
  INDEX `fk_t_user_attendance_detail_t_user_attended1_idx` (`fk_atid` ASC),
  CONSTRAINT `fk_t_user_attendance_detail_t_user_attended1`
    FOREIGN KEY (`fk_atid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_attendance` (`pk_atid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_attendance_t_user_attendance_signin_type1`
    FOREIGN KEY (`fk_signinid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_attendance_signin_type` (`pk_sitid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_attendance_t_user_attendance_signout_type1`
    FOREIGN KEY (`fk_signoutid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_attendance_signout_type` (`pk_sotid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_performance` (
  `pk_epid` INT(11) NOT NULL,
  `reward` DOUBLE NULL DEFAULT NULL,
  `punishment` DOUBLE NULL DEFAULT NULL,
  `month` DATE NOT NULL,
  `fk_eid` INT(11) NOT NULL,
  PRIMARY KEY (`pk_epid`),
  INDEX `fk_t_employee_performance_t_employee_infomation1_idx` (`fk_eid` ASC),
  CONSTRAINT `fk_t_employee_performance_t_employee_infomation1`
    FOREIGN KEY (`fk_eid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_infomation` (`pk_eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_salary` (
  `pk_esid` INT(11) NOT NULL AUTO_INCREMENT,
  `salary` DOUBLE NULL DEFAULT NULL,
  `month` VARCHAR(45) NULL DEFAULT NULL,
  `fk_eid` INT(11) NOT NULL,
  PRIMARY KEY (`pk_esid`),
  INDEX `fk_t_employee_salary_t_employee_infomation1_idx` (`fk_eid` ASC),
  CONSTRAINT `fk_t_employee_salary_t_employee_infomation1`
    FOREIGN KEY (`fk_eid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_infomation` (`pk_eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_infomation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_infomation` (
  `pk_uid` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_uid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_leave_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_leave_type` (
  `pk_tid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_tid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_leave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_leave` (
  `pk_lid` INT(11) NOT NULL,
  `proposer` VARCHAR(45) NOT NULL,
  `fk_verifierid` INT(11) NOT NULL,
  `start` DATE NOT NULL,
  `end` DATE NOT NULL,
  `reason` VARCHAR(100) NOT NULL,
  `fk_ltid` INT(11) NOT NULL,
  `fk_Proposerid` INT(11) NOT NULL,
  PRIMARY KEY (`pk_lid`),
  INDEX `fk_t_user_leave_t_user_information2_idx` (`fk_verifierid` ASC),
  INDEX `fk_t_user_leave_t_user_leave_type1_idx` (`fk_ltid` ASC),
  INDEX `fk_t_user_leave_t_employee_infomation1_idx` (`fk_Proposerid` ASC),
  CONSTRAINT `fk_t_user_leave_t_employee_infomation1`
    FOREIGN KEY (`fk_Proposerid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_infomation` (`pk_eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_leave_t_user_information2`
    FOREIGN KEY (`fk_verifierid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_infomation` (`pk_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_leave_t_user_leave_type1`
    FOREIGN KEY (`fk_ltid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_leave_type` (`pk_tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_role` (
  `pk_roid` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_roid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_role_permission` (
  `pk_perid` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_perid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_role_permission_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_role_permission_session` (
  `pk_roid` INT(11) NOT NULL,
  `pk_perid` INT(11) NOT NULL,
  PRIMARY KEY (`pk_roid`, `pk_perid`),
  INDEX `fk_t_user_role_has_t_user_role_permission_t_user_role_permi_idx` (`pk_perid` ASC),
  INDEX `fk_t_user_role_has_t_user_role_permission_t_user_role1_idx` (`pk_roid` ASC),
  CONSTRAINT `fk_t_user_role_has_t_user_role_permission_t_user_role1`
    FOREIGN KEY (`pk_roid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_role` (`pk_roid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_role_has_t_user_role_permission_t_user_role_permiss1`
    FOREIGN KEY (`pk_perid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_role_permission` (`pk_perid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_role_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_role_session` (
  `pk_uid` INT(11) NOT NULL,
  `pk_roid` INT(11) NOT NULL,
  PRIMARY KEY (`pk_uid`, `pk_roid`),
  INDEX `fk_t_user_information_has_t_user_role_t_user_role1_idx` (`pk_roid` ASC),
  INDEX `fk_t_user_information_has_t_user_role_t_user_information1_idx` (`pk_uid` ASC),
  CONSTRAINT `fk_t_user_information_has_t_user_role_t_user_information1`
    FOREIGN KEY (`pk_uid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_infomation` (`pk_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_information_has_t_user_role_t_user_role1`
    FOREIGN KEY (`pk_roid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_role` (`pk_roid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
