-- MySQL Script generated by MySQL Workbench
-- Sat Mar 21 16:21:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema d_PersonnelManagementSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema d_PersonnelManagementSystem
-- -----------------------------------------------------
drop database `d_PersonnelManagementSystem`;
CREATE SCHEMA IF NOT EXISTS `d_PersonnelManagementSystem` DEFAULT CHARACTER SET utf8 ;
USE `d_PersonnelManagementSystem` ;

-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_archives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_archives` (
  `pk_aid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `sex` VARCHAR(20) NOT NULL,
  `img` VARCHAR(100) NULL,
  `idcard` VARCHAR(18) CHARACTER SET 'utf8' NOT NULL,
  `native place` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT '籍贯',
  `politics status` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL COMMENT '政治面貌',
  `tel` INT NOT NULL,
  `eMail` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `education` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT '学历',
  `university` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT '大学',
  `major` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT '专业',
  `linkmanname` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT '紧急联系人姓名',
  `linkmantel` INT NOT NULL COMMENT '紧急联系人电话',
  `linkmanRelation` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT '紧急联系人关系',
  PRIMARY KEY (`pk_aid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `idcard_UNIQUE` (`idcard` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '员工档案';


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_department` (
  `pk_did` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`pk_did`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_position` (
  `pk_pid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `saraly` DOUBLE NOT NULL,
  `fk_did` INT NOT NULL,
  PRIMARY KEY (`pk_pid`),
  INDEX `fk_t_employee_position_t_employee_department1_idx` (`fk_did` ASC),
  CONSTRAINT `fk_t_employee_position_t_employee_department1`
    FOREIGN KEY (`fk_did`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_department` (`pk_did`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_employee_infomation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_employee_infomation` (
  `pk_eid` INT NOT NULL AUTO_INCREMENT,
  `fk_pid` INT NOT NULL,
  `fk_aid` INT NOT NULL,
  `jointime` DATE NULL,
  `training` VARCHAR(100) CHARACTER SET 'utf8' NULL,
  `boss` INT NULL,
  PRIMARY KEY (`pk_eid`),
  INDEX `fk_t_employee_infomation_t_employee_position1_idx` (`fk_pid` ASC),
  INDEX `fk_t_employee_infomation_t_employee_archives1_idx` (`fk_aid` ASC),
  CONSTRAINT `fk_t_employee_infomation_t_employee_position1`
    FOREIGN KEY (`fk_pid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_position` (`pk_pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_employee_infomation_t_employee_archives1`
    FOREIGN KEY (`fk_aid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_archives` (`pk_aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_information` (
  `pk_uid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fk_eid` INT NOT NULL,
  PRIMARY KEY (`pk_uid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_t_user_information_t_employee_infomation1_idx` (`fk_eid` ASC),
  CONSTRAINT `fk_t_user_information_t_employee_infomation1`
    FOREIGN KEY (`fk_eid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_employee_infomation` (`pk_eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_announcement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_announcement` (
  `pk_anid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `details` VARCHAR(500) NOT NULL,
  `crttime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_uid` INT NOT NULL,
  PRIMARY KEY (`pk_anid`),
  INDEX `fk_t_user_ Announcement_t_user_information1_idx` (`fk_uid` ASC),
  CONSTRAINT `fk_t_user_ Announcement_t_user_information1`
    FOREIGN KEY (`fk_uid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_information` (`pk_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_file` (
  `pk_fid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `addr` VARCHAR(100) NOT NULL,
  `crttime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_uid` INT NOT NULL,
  PRIMARY KEY (`pk_fid`),
  INDEX `fk_t_user_file_t_user_information1_idx` (`fk_uid` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_t_user_file_t_user_information1`
    FOREIGN KEY (`fk_uid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_information` (`pk_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_leave_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_leave_type` (
  `pk_tid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_tid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_leave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_leave` (
  `pk_lid` INT NOT NULL AUTO_INCREMENT,
  `proposer` VARCHAR(45) NOT NULL,
  `fk_proposerid` INT NOT NULL,
  `fk_verifierid` INT NOT NULL,
  `start` DATE NOT NULL,
  `end` DATE NOT NULL,
  `reason` VARCHAR(100) NOT NULL,
  `fk_ltid` INT NOT NULL,
  PRIMARY KEY (`pk_lid`),
  INDEX `fk_t_user_leave_t_user_information1_idx` (`fk_proposerid` ASC),
  INDEX `fk_t_user_leave_t_user_information2_idx` (`fk_verifierid` ASC),
  INDEX `fk_t_user_leave_t_user_leave_type1_idx` (`fk_ltid` ASC),
  CONSTRAINT `fk_t_user_leave_t_user_information1`
    FOREIGN KEY (`fk_proposerid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_information` (`pk_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_leave_t_user_information2`
    FOREIGN KEY (`fk_verifierid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_information` (`pk_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_leave_t_user_leave_type1`
    FOREIGN KEY (`fk_ltid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_leave_type` (`pk_tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_attendance_signout_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_attendance_signout_type` (
  `pk_sotid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_sotid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_attendance_signin_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_attendance_signin_type` (
  `pk_sitid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_sitid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_attendance_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_attendance_time` (
  `pk_attid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `start` TIME NOT NULL,
  `end` TIME NOT NULL,
  PRIMARY KEY (`pk_attid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_attendance` (
  `pk_atid` INT NOT NULL AUTO_INCREMENT,
  `fk_attid` INT NOT NULL,
  `fk_uid` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`pk_atid`),
  INDEX `fk_t_user_attended_t_user_attended_time1_idx` (`fk_attid` ASC),
  INDEX `fk_t_user_attended_t_user_information1_idx` (`fk_uid` ASC),
  CONSTRAINT `fk_t_user_attended_t_user_attended_time1`
    FOREIGN KEY (`fk_attid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_attendance_time` (`pk_attid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_attended_t_user_information1`
    FOREIGN KEY (`fk_uid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_information` (`pk_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_attendance_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_attendance_detail` (
  `pk_atdid` INT NOT NULL AUTO_INCREMENT,
  `fk_signoutid` INT NOT NULL,
  `fk_signinid` INT NOT NULL,
  `isleave` INT NULL,
  `fk_atid` INT NOT NULL,
  PRIMARY KEY (`pk_atdid`),
  INDEX `fk_t_user_attendance_t_user_attendance_signout_type1_idx` (`fk_signoutid` ASC),
  INDEX `fk_t_user_attendance_t_user_attendance_signin_type1_idx` (`fk_signinid` ASC),
  INDEX `fk_t_user_attendance_detail_t_user_attended1_idx` (`fk_atid` ASC),
  CONSTRAINT `fk_t_user_attendance_t_user_attendance_signout_type1`
    FOREIGN KEY (`fk_signoutid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_attendance_signout_type` (`pk_sotid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_attendance_t_user_attendance_signin_type1`
    FOREIGN KEY (`fk_signinid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_attendance_signin_type` (`pk_sitid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_attendance_detail_t_user_attended1`
    FOREIGN KEY (`fk_atid`)
    REFERENCES `d_PersonnelManagementSystem`.`t_user_attendance` (`pk_atid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `d_PersonnelManagementSystem`.`t_user_attendance_signin_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_PersonnelManagementSystem`.`t_user_attendance_signin_type` (
  `pk_sitid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_sitid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
